---
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          sudo apt-get update && sudo apt-get install -y libgraphviz-dev
          pip install -r requirements.txt
          ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/graphviz
          pip install --global-option=build_ext --global-option="-I/usr/include/graphviz" --global-option="-L/usr/lib/x86_64-linux-gnu/" --install-option="--library-path=/usr/lib/x86_64-linux-gnu/graphviz" pygraphviz
      - name: Run tox targets for ${{ matrix.python-version }}
        run: |
          source venv/bin/activate
          pytest